In [1]:
import pandas as pd
import numpy as np

In [2]:
codesignLGA = pd.read_csv('./CoDesign_Projections/CoDesign_Projections_LGA.csv')
codesignLocality = pd.read_csv('./CoDesign_Projections/CoDesign_Projections_LocalitySplitAtLGAs.csv')
fidLGA = pd.read_csv('./ForecastID_Projections/output/ForecastID_Projections_LGA.csv')
fidLocality = pd.read_csv('./ForecastID_Projections/output/ForecastID_Projections_Locality.csv')

### Clean datasets

In [3]:
codesignLGA.columns

Index(['lga_name16', 'ERP_2016', 'ERP_2021', 'ERP_2026', 'ERP_2031',
       'ERP_2036', 'ERP_2041', 'ERP_2046', 'ERP_2051', 'ERP_2056', 'EMP_2016',
       'EMP_2021', 'EMP_2026', 'EMP_2031', 'EMP_2036', 'EMP_2041', 'EMP_2046',
       'EMP_2051', 'EMP_2056'],
      dtype='object')

In [4]:
codesignLocality.columns

Index(['Locality', 'LGA', 'Split_id', 'ERP_2016', 'ERP_2056', 'EMP_2016',
       'EMP_2056'],
      dtype='object')

In [6]:
fidLGA.columns

Index(['Area', 'LGA_fid', '2016', '2036', '2041', 'LGA'], dtype='object')

In [7]:
fidLocality.columns

Index(['Area', 'LGA_fid', '2016', '2036', '2041', 'LGA'], dtype='object')

### Combine Locality projections

In [8]:
codesignLocality.head()

,Locality,LGA,Split_id,ERP_2016,ERP_2056,EMP_2016,EMP_2056
0,ABBOTSBURY,Fairfield (C),1764,6297.0,7102.0,723.0,1087.0
1,ABBOTSFORD,Canada Bay (A),1568,5601.0,6849.0,803.0,1354.0
2,ACACIA GARDENS,Blacktown (C),1230,3958.0,5502.0,289.0,721.0
3,AGNES BANKS,Penrith (C),1319,1392.0,1490.0,421.0,508.0
4,AIRDS,Campbelltown (C) (NSW),526,2999.0,5305.0,592.0,906.0

In [9]:
len(codesignLocality)

724

In [10]:
fidLocality.head()

,Area,LGA_fid,2016,2036,2041,LGA
0,Abbotsbury,Fairfield City,4439.0,4581.0,NaN,Fairfield (C)
1,Abbotsford - Wareemba,"Burwood, City of Canada Bay and Strathfield Mu...",7323.0,7325.0,NaN,"Burwood, Canada Bay (A) and Strathfield Munici..."
2,Abbotsford - Wareemba,City of Canada Bay,7323.0,7325.0,NaN,Canada Bay (A)
3,Acacia Gardens - Parklea,Blacktown City,7492.0,7694.0,NaN,Blacktown (C)
4,Airds,Campbelltown City,3082.0,5108.0,NaN,Campbelltown (C) (NSW)

In [11]:
len(fidLocality)

488

In [12]:
localities = list(codesignLocality['Locality'].str.lower())

In [13]:
fidLocality['Area_match'] = fidLocality['Area'].apply(lambda x: x.upper() if x.lower() in localities else '')
fidLocality.head()

,Area,LGA_fid,2016,2036,2041,LGA,Area_match
0,Abbotsbury,Fairfield City,4439.0,4581.0,NaN,Fairfield (C),ABBOTSBURY
1,Abbotsford - Wareemba,"Burwood, City of Canada Bay and Strathfield Mu...",7323.0,7325.0,NaN,"Burwood, Canada Bay (A) and Strathfield Munici...",
2,Abbotsford - Wareemba,City of Canada Bay,7323.0,7325.0,NaN,Canada Bay (A),
3,Acacia Gardens - Parklea,Blacktown City,7492.0,7694.0,NaN,Blacktown (C),
4,Airds,Campbelltown City,3082.0,5108.0,NaN,Campbelltown (C) (NSW),AIRDS

In [14]:
len(fidLocality.loc[fidLocality['Area_match']==''])

176

In [15]:
print(len(codesignLocality))
combinedLocalities = codesignLocality.merge(fidLocality, how='left', right_on=['Area_match','LGA'], left_on=['Locality','LGA']).drop('Area_match',axis=1)
print(len(combinedLocalities))

724
724

In [16]:
combinedLocalities.head()

,Locality,LGA,Split_id,ERP_2016,ERP_2056,EMP_2016,EMP_2056,Area,LGA_fid,2016,2036,2041
0,ABBOTSBURY,Fairfield (C),1764,6297.0,7102.0,723.0,1087.0,Abbotsbury,Fairfield City,4439.0,4581.0,NaN
1,ABBOTSFORD,Canada Bay (A),1568,5601.0,6849.0,803.0,1354.0,NaN,NaN,NaN,NaN,NaN
2,ACACIA GARDENS,Blacktown (C),1230,3958.0,5502.0,289.0,721.0,NaN,NaN,NaN,NaN,NaN
3,AGNES BANKS,Penrith (C),1319,1392.0,1490.0,421.0,508.0,NaN,NaN,NaN,NaN,NaN
4,AIRDS,Campbelltown (C) (NSW),526,2999.0,5305.0,592.0,906.0,Airds,Campbelltown City,3082.0,5108.0,NaN

In [17]:
fidUnmatchedLocalities = fidLocality.loc[fidLocality['Area_match']=='']
print(len(fidUnmatchedLocalities))
fidUnmatchedLocalities.head()

176

,Area,LGA_fid,2016,2036,2041,LGA,Area_match
1,Abbotsford - Wareemba,"Burwood, City of Canada Bay and Strathfield Mu...",7323.0,7325.0,NaN,"Burwood, Canada Bay (A) and Strathfield Munici...",
2,Abbotsford - Wareemba,City of Canada Bay,7323.0,7325.0,NaN,Canada Bay (A),
3,Acacia Gardens - Parklea,Blacktown City,7492.0,7694.0,NaN,Blacktown (C),
5,Alex Avenue Release Area,Blacktown City,4408.0,19174.0,NaN,Blacktown (C),
9,Ambarvale - Englorie Park,Campbelltown City,7730.0,7748.0,NaN,Campbelltown (C) (NSW),

In [18]:
combinedLocalities.to_csv('combinedLocalityProjections.csv', index=False)
fidUnmatchedLocalities.to_csv('unmatchedForecastIdLocalityProjections.csv', index=False)