In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
accessdf = pd.read_csv('Access_LiverpoolLGA_Uniform.csv')
accessdf.head()

    locality           Jobs  cutoff  X  T_freq  L_freq
0  Liverpool    4675.974992      15  1     0.0     1.0
1  Liverpool   40539.922655      30  1     0.0     1.0
2  Liverpool  154535.993446      45  1     0.0     1.0
3  Liverpool  516845.375888      60  1     0.0     1.0
4  Liverpool    4508.858989      15  2     0.0     2.0

In [3]:
accessdf['T_freqPerHr'] = accessdf['T_freq'].apply(lambda x: 0 if x==0 else 60/x).astype(int)
accessdf['L_freqPerHr'] = accessdf['L_freq'].apply(lambda x: 0 if x==0 else 60/x).astype(int)
accessdf.columns = ['locality','Jobs','cutoff','X','T_f','L_f','T_freq','L_freq']
accessdf.head()

    locality           Jobs  cutoff  X  T_f  L_f  T_freq  L_freq
0  Liverpool    4675.974992      15  1  0.0  1.0       0      60
1  Liverpool   40539.922655      30  1  0.0  1.0       0      60
2  Liverpool  154535.993446      45  1  0.0  1.0       0      60
3  Liverpool  516845.375888      60  1  0.0  1.0       0      60
4  Liverpool    4508.858989      15  2  0.0  2.0       0      30

In [4]:
access15 = accessdf.loc[accessdf['cutoff']==15]
access30 = accessdf.loc[accessdf['cutoff']==30]
access45 = accessdf.loc[accessdf['cutoff']==45]
access60 = accessdf.loc[accessdf['cutoff']==60]

In [8]:
reg15 = smf.ols('Jobs ~ T_freq + L_freq', data = access15).fit()
#reg15 = smf.ols('Jobs ~ T_freq + L_freq -1', data = access15).fit()
reg15.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Jobs   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.910
Method:                 Least Squares   F-statistic:                     235.0
Date:                Thu, 10 Dec 2020   Prob (F-statistic):           3.28e-24
Time:                        12:18:51   Log-Likelihood:                -271.23
No. Observations:                  47   AIC:                             548.5
Df Residuals:                      44   BIC:                             554.0
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   3978.1274     15.849    251.003      0.000    3946.186    4010.069
T_freq         2.6269      0.634      4.146      0.000       1.350       3.904
L_freq        12.0880      0.634     19.077      0.000      10.811      13.365
==============================================================================
Omnibus:                        3.681   Durbin-Watson:                   0.633
Prob(Omnibus):                  0.159   Jarque-Bera (JB):                3.244
Skew:                           0.555   Prob(JB):                        0.197
Kurtosis:                       2.349   Cond. No.                         40.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [11]:
reg30 = smf.ols('Jobs ~ T_freq + L_freq', data = access30).fit()
#reg30 = smf.ols('Jobs ~ T_freq + L_freq -1', data = access30).fit()
reg30.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Jobs   R-squared:                       0.718
Model:                            OLS   Adj. R-squared:                  0.705
Method:                 Least Squares   F-statistic:                     56.06
Date:                Thu, 10 Dec 2020   Prob (F-statistic):           7.95e-13
Time:                        12:19:49   Log-Likelihood:                -436.90
No. Observations:                  47   AIC:                             879.8
Df Residuals:                      44   BIC:                             885.4
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   3.048e+04    538.087     56.654      0.000    2.94e+04    3.16e+04
T_freq        93.1415     21.513      4.330      0.000      49.786     136.497
L_freq       170.6869     21.513      7.934      0.000     127.331     214.043
==============================================================================
Omnibus:                        1.951   Durbin-Watson:                   0.405
Prob(Omnibus):                  0.377   Jarque-Bera (JB):                1.837
Skew:                          -0.399   Prob(JB):                        0.399
Kurtosis:                       2.452   Cond. No.                         40.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
reg45 = smf.ols('Jobs ~ T_freq + L_freq', data = access45).fit()
#reg45 = smf.ols('Jobs ~ T_freq + L_freq -1', data = access45).fit()
reg45.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Jobs   R-squared:                       0.606
Model:                            OLS   Adj. R-squared:                  0.589
Method:                 Least Squares   F-statistic:                     33.91
Date:                Thu, 10 Dec 2020   Prob (F-statistic):           1.23e-09
Time:                        12:20:39   Log-Likelihood:                -498.74
No. Observations:                  47   AIC:                             1003.
Df Residuals:                      44   BIC:                             1009.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1.271e+05   2005.620     63.375      0.000    1.23e+05    1.31e+05
T_freq       327.3926     80.184      4.083      0.000     165.791     488.994
L_freq       449.8495     80.184      5.610      0.000     288.248     611.451
==============================================================================
Omnibus:                       12.380   Durbin-Watson:                   0.486
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               12.551
Skew:                          -1.127   Prob(JB):                      0.00188
Kurtosis:                       4.153   Cond. No.                         40.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [17]:
reg60 = smf.ols('Jobs ~ T_freq + L_freq', data = access60).fit()
#reg60 = smf.ols('Jobs ~ T_freq + L_freq -1', data = access60).fit()
reg60.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Jobs   R-squared:                       0.586
Model:                            OLS   Adj. R-squared:                  0.567
Method:                 Least Squares   F-statistic:                     31.11
Date:                Thu, 10 Dec 2020   Prob (F-statistic):           3.80e-09
Time:                        12:21:10   Log-Likelihood:                -533.09
No. Observations:                  47   AIC:                             1072.
Df Residuals:                      44   BIC:                             1078.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   4.633e+05   4165.112    111.224      0.000    4.55e+05    4.72e+05
T_freq       698.6763    166.521      4.196      0.000     363.076    1034.277
L_freq       853.6492    166.521      5.126      0.000     518.049    1189.250
==============================================================================
Omnibus:                       15.558   Durbin-Watson:                   0.487
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               17.677
Skew:                          -1.266   Prob(JB):                     0.000145
Kurtosis:                       4.618   Cond. No.                         40.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""